events_events:
    resource: "@eventsBundle/Resources/config/routing/events.yml"
    prefix:   /events

events_homepage:
    path:     /a
    defaults: {_controller: eventsBundle:Default:index}
events:
    path:     /events
    defaults: {_controller: eventsBundle:Events:index}
events_index:
  path:     /
  defaults: { _controller: "eventsBundle:Events:index" }
  methods:  GET

events_show:
  path:     /{idEvent}/show
  defaults: { _controller: "eventsBundle:Events:show" }
  methods:  GET

events_new:
  path:     /new
  defaults: { _controller: "eventsBundle:Events:new" }
  methods:  [GET, POST]

events_edit:
  path:     /{idEvent}/edit
  defaults: { _controller: "eventsBundle:Events:edit" }
  methods:  [GET, POST]

events_delete:
  path:     /{idEvent}/delete
  defaults: { _controller: "eventsBundle:Events:delete" }
  methods:  DELETE
